<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Usuario extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    }

    /*
     * Listing of usuarios
     */
    function index()
    {
        if (isset($this->session->userdata['logged_in'])) {
            $data['usuarios'] = $this->Usuario_model->get_all_usuarios();

            $data['_view'] = 'usuario/index';
            $this->load->view('layouts/main', $data);
        } else {
            $dat['_view'] = 'dashboard1';
            $this->load->view('layouts/main', $dat);
        }
    }

    /*
     * Adding a new usuario
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('Correo', 'Correo', 'valid_email');

        if ($this->form_validation->run()) {
            $params = array(
                'Contraseña' => $this->input->post('Contraseña'),
                'Usuario' => $this->input->post('Usuario'),
                'Correo' => $this->input->post('Correo'),
                'Rol' => $this->input->post('Rol'),
            );

            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        } else {
            $data['_view'] = 'usuario/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a usuario
     */
    function edit($idusuario)
    {
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($idusuario);

        if (isset($data['usuario']['idusuario'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('Correo', 'Correo', 'valid_email');

            if ($this->form_validation->run()) {
                $params = array(
                    'Usuario' => $this->input->post('Usuario'),
                    'Contraseña' => $this->input->post('Contraseña'),
                    'Correo' => $this->input->post('Correo'),
                    'Rol' => $this->input->post('Rol'),
                );

                $this->Usuario_model->update_usuario($idusuario, $params);
                redirect('usuario/index');
            } else {
                $data['_view'] = 'usuario/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('El Usuario no existe.');
    }

    /*
     * Deleting usuario
     */
    function remove($idusuario)
    {
        $usuario = $this->Usuario_model->get_usuario($idusuario);

        // check if the usuario exists before trying to delete it
        if (isset($usuario['idusuario'])) {
            $this->Usuario_model->delete_usuario($idusuario);
            redirect('usuario/index');
        } else
            show_error('El Usuario no existe.');
    }
}
