<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get usuario by idusuario
     */
    function get_usuario($idusuario)
    {
        return $this->db->get_where('usuario', array('idusuario' => $idusuario))->row_array();
    }

    function get_nombre($idusuario)
    {
        $query = $this->db->select('Usuario')
            ->from('usuario')
            ->where('idusuario', $idusuario)
            ->get();
        return $query->row_array();
    }

    function get_cajeros()
    {
        $query = $this->db->select('*')
            ->from('usuario')
            ->where('Rol', 'User')
            ->get();
        return $query->result_array();
    }

    function logear($usuario, $contraseña)
    {
        $this->db->select('*');
        $this->db->from('usuario');
        $this->db->where('Usuario', $usuario);
        $this->db->where('Contraseña', $contraseña);
        $this->db->where('Rol', 'Admin');
        //$this->db->limit(1);
        $query = $this->db->get();
        if ($query->num_rows() == 1) {
            //print_r($query->result());
            //return $query->result();
            return true;
        } else {
            return false;
        }
    }

    /*
     * Get all usuarios
     */
    function get_all_usuarios()
    {
        $this->db->order_by('idusuario', 'asc');
        return $this->db->get('usuario')->result_array();
    }

    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update usuario
     */
    function update_usuario($idusuario, $params)
    {
        $this->db->where('idusuario', $idusuario);
        return $this->db->update('usuario', $params);
    }

    /*
     * function to delete usuario
     */
    function delete_usuario($idusuario)
    {
        return $this->db->delete('usuario', array('idusuario' => $idusuario));
    }
}
